import data from './mock/users.json'; // generated by randomuser.me

const ROUND_TRIP = 500;

let currentRequest;

export const search = query => new Promise((resolve) => {
  if (currentRequest) clearTimeout(currentRequest);

  currentRequest = setTimeout(() => {
    if (!query) return resolve(data);

    const regexp = new RegExp(`^${query}`, 'ig');
    const res = data.filter(user => regexp.test(user.name.first) || regexp.test(user.name.last));

    return resolve(res);
  }, ROUND_TRIP);
});
